### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #30.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/opencv-feedstock/pull/181

**Comment by ocefpaf** [comment]
@hmaarrfk If you need a new package we need to bump the build number.

**Comment by hmaarrfk** [comment]
Is there a magical command for the bot to do it for me? Not sure I have write access

**Comment by ocefpaf** [comment]
> Is there a magical command for the bot to do it for me? Not sure I have write access

I don't think so. I made the modifications. (I assumed you had access here. BTW, consider adding yourself as a maintainer ;-p)

**Comment by hmaarrfk** [comment]
Myabe we are hitting this https://savannah.nongnu.org/bugs/?54846

**Comment by ocefpaf** [comment]
> Myabe we are hitting this https://savannah.nongnu.org/bugs/?54846

AppVeyor is passing so we don't need to fix that now.

**Pull request merged**
