### PR TITLE
Install the pkg-config file on Windows too.

### PR DESCRIPTION
**Pull request by pkgw**
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pkgw** [comment]
Crap, should not be merged just yet. There's a problem with conda-build rewriting the paths in the pkg-config files correctly, I think because they used mixed-style ("C:/foo/bar") Windows paths.

**Comment by ocefpaf** [comment]
> Crap, should not be merged just yet. There's a problem with conda-build rewriting the paths in the pkg-config files correctly, I think because they used mixed-style ("C:/foo/bar") Windows paths.

OK. Pinging @msarahan and @mingwandroid here for advice.

**Comment by pkgw** [comment]
Reading conda-build, it looks like it does handle all the variant ways that Windows paths might be stored as text. Maybe an issue with capitalization changing? Investigating ...

**Comment by pkgw** [comment]
Yes, I think it's because the capitalization of the path is different in the generated file than what conda-build knows. In *principle* I think conda-build could handle this, but it sure sounds like that would be a hassle. I'll see if I can figure out some workarounds.

**Comment by pkgw** [comment]
Ah. In particular, CMake seems to like to decapitalize all of the paths that it processes on Windows. So if you ever switched to building things in `C:\BLD` rather than `C:\bld`, I think that suddenly many Windows packages would start breaking in exciting ways.

**Comment by pkgw** [comment]
OK, I've convinced myself that everything stays in order if you build your packages in the right prefix. In which case I think this PR is ready for review.

**Pull request merged**
