### PR TITLE
Test a build for vc10

### PR DESCRIPTION
**Pull request by ocefpaf**
xref.: https://github.com/conda-forge/matplotlib-feedstock/pull/210

Ping @dopplershift

### CODE REVIEW

**Comment by ocefpaf** [comment]
@dopplershift looking into this it seems that it will be easier to update the matplotlib tests than to get a build of `freetype 2.6.1` in conda-forge :-/

**Comment by dopplershift** [comment]
That’s going to be a longer term problem for matplotlib.

**Comment by ocefpaf** [comment]
> That’s going to be a longer term problem for matplotlib.

I'm looking into alternatives here too but I'll be away next week. I'll ping you once I get back.

**Comment by ocefpaf** [comment]
Closing this as stale.

**Pull request closed without merging**
